# Generated by Django 2.0.3 on 2018-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
