# Generated by Django 2.0.3 on 2018-03-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
