# Generated by Django 2.0.3 on 2018-04-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20180402_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcat',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
